python -u run.py \
  --is_training 1 \
  --gpu 4 \
  --start 2000 \
  --train_start 2000\
  --train_size 3 \
  --val_size 2 \
  --test_size 30 \
  --test_end_year 2023\
  --root_path ./dataset/ \
  --data_path us_con.feather \
  --full True\
  --model_id us_64_1 \
  --model Dlinear \
  --exp Main\
  --data custom \
  --market us \
  --features D \
  --train_epochs 10\
  --batch_size 512\
  --seq_len 64 \
  --pred_len 1 \
  --train_label_len 1\
  --e_layers 1 \
  --d_layers 1 \
  --enc_in 7 \
  --d_model 32\
  --c_out 1 \
  --des 'Exp' \
  --itr 1